Add tsconfig to fix angular issue
I got error when I upgrade my angular project to nativescript 6
```
ERROR in ../node_modules/nativescript-i18n/angular.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /home/xlmnxp/Projects/yahmini/node_modules/nativescript-i18n/angular.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
```

I think add tsconfig will fix issue